#!/bin/bash

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

        echo 'graph_title 4.Wind direction of Nagano-shi, Nagano Prefecture'
#        echo 'graph_args --base 1000 -l 0'
	echo 'graph_args --lower-limit 0 --upper-limit 360 --rigid'
        echo 'graph_vlabel Wind Direction (degrees)'
        echo 'graph_scale no'
        echo 'graph_category weather_nagano'
        echo 'graph_info Wind Direction'
        echo 'kazamuki.label Wind Direction (degrees)'
        echo 'kazamuki.info MUNIN-EX.php'
	echo 'kazamuki.draw LINE2'
	echo 'kazamuki.min 0'
	echo 'kazamuki.max 360'
	echo 'kazamuki.colour 8D00BA'
        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi


/home/kouji/public_html/html/AutoTweet/MUNIN/MUNIN-EX.php kazamuki nagano_prefs.xml
