#!/bin/bash

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

        echo 'graph_title 2.Humidity and Clouds value of Naha, Okinawa Prefecture'
#        echo 'graph_args --base 1000 -l 0'
	echo 'graph_args --lower-limit 0 --upper-limit 100 --rigid'
        echo 'graph_vlabel            '
        echo 'graph_scale no'
        echo 'graph_category weather_Naha'
        echo 'graph_info Humidity and Clouds Value'
        echo 'humidity.label Humidity (%)'
        echo 'humidity.info MUNIN-EX.php'
	echo 'humidity.draw LINE2'
	echo 'humidity.max 100'
	echo 'humidity.colour 00FF00'
        echo 'clouds.label Clouds Value (%)'
        echo 'clouds.info MUNIN-EX.php'
	echo 'clouds.draw LINE2'
	echo 'clouds.max 100'
	echo 'clouds.colour AFECED'
        echo 'discomfort.label Discomfort Index'
        echo 'discomfort.info MUNIN-EX.php'
	echo 'discomfort.draw LINE1'
	echo 'discomfort.max 100'
	echo 'discomfort.colour 008800'
        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi

/home/kouji/public_html/html/AutoTweet/MUNIN/MUNIN-EX.php humidity-and-clouds okinawa_prefs.xml
